#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Apr 07, 2020 11:05:34 PM CEST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #091833 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1028x500+133+152
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1362 741
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Restaurant Management"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab44 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 20 -weight bold} -foreground #f2a343 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Restaurant Management System} 
    vTcl:DefineAlias "$top.lab44" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Order Num:} 
    vTcl:DefineAlias "$top.lab45" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.lab45.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    vTcl:DefineAlias "$top.lab45.ent52" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$top.lab45.lab53" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.lab45.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 254 
    vTcl:DefineAlias "$top.lab45.ent55" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Chicken Burger:} 
    vTcl:DefineAlias "$top.lab46" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Fried Potato:} 
    vTcl:DefineAlias "$top.lab47" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Big King:} 
    vTcl:DefineAlias "$top.lab48" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Chicken Royal:} 
    vTcl:DefineAlias "$top.lab49" "Label2_4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Vegan Salad:} 
    vTcl:DefineAlias "$top.lab50" "Label2_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground darkcyan \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Drinks: 
    vTcl:DefineAlias "$top.lab51" "Label2_6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent56" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent57 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent57" "Entry3_7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent58 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent58" "Entry3_8" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent59" "Entry3_9" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent60" "Entry3_10" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent61 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent61" "Entry3_11" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent62 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent62" "Entry3_12" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #e16740 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Cost: 
    vTcl:DefineAlias "$top.lab64" "Label2_13" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Service charge:} 
    vTcl:DefineAlias "$top.lab65" "Label2_14" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Tax: 
    vTcl:DefineAlias "$top.lab66" "Label2_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Subtotal: 
    vTcl:DefineAlias "$top.lab67" "Label2_2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #091833 \
        -disabledforeground #a3a3a3 \
        -font {-family {Ebrima} -size 16 -weight bold} -foreground #bac8bd \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Total: 
    vTcl:DefineAlias "$top.lab68" "Label2_3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent69 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent69" "Entry3_15" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent70 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 134 
    vTcl:DefineAlias "$top.ent70" "Entry3_16" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent71 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent71" "Entry3_17" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent72 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 164 
    vTcl:DefineAlias "$top.ent72" "Entry3_18" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent73 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 184 
    vTcl:DefineAlias "$top.ent73" "Entry3_19" vTcl:WidgetProc "Toplevel1" 1
    button $top.but74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e16740 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text PRICE 
    vTcl:DefineAlias "$top.but74" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e16740 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text TOTAL 
    vTcl:DefineAlias "$top.but75" "Button1_20" vTcl:WidgetProc "Toplevel1" 1
    button $top.but76 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e16740 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text RESET 
    vTcl:DefineAlias "$top.but76" "Button1_21" vTcl:WidgetProc "Toplevel1" 1
    button $top.but77 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #e16740 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 13 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text EXIT 
    vTcl:DefineAlias "$top.but77" "Button1_22" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent78 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Arial} -size 10 -weight bold} -foreground #c60000 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #f2a343 \
        -selectforeground black -width 254 
    vTcl:DefineAlias "$top.ent78" "Entry3_23" vTcl:WidgetProc "Toplevel1" 1
    button $top.but79 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 7 
    vTcl:DefineAlias "$top.but79" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but80 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 8 
    vTcl:DefineAlias "$top.but80" "Button2_24" vTcl:WidgetProc "Toplevel1" 1
    button $top.but81 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 9 
    vTcl:DefineAlias "$top.but81" "Button2_25" vTcl:WidgetProc "Toplevel1" 1
    button $top.but82 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 4 
    vTcl:DefineAlias "$top.but82" "Button2_26" vTcl:WidgetProc "Toplevel1" 1
    button $top.but83 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 6 
    vTcl:DefineAlias "$top.but83" "Button2_27" vTcl:WidgetProc "Toplevel1" 1
    button $top.but84 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 1 
    vTcl:DefineAlias "$top.but84" "Button2_28" vTcl:WidgetProc "Toplevel1" 1
    button $top.but85 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 2 
    vTcl:DefineAlias "$top.but85" "Button2_29" vTcl:WidgetProc "Toplevel1" 1
    button $top.but86 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 3 
    vTcl:DefineAlias "$top.but86" "Button2_30" vTcl:WidgetProc "Toplevel1" 1
    button $top.but87 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 5 
    vTcl:DefineAlias "$top.but87" "Button2_31" vTcl:WidgetProc "Toplevel1" 1
    button $top.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text . 
    vTcl:DefineAlias "$top.but88" "Button2_4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but89 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 0 
    vTcl:DefineAlias "$top.but89" "Button2_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but90 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text C 
    vTcl:DefineAlias "$top.but90" "Button2_6" vTcl:WidgetProc "Toplevel1" 1
    button $top.but91 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text / 
    vTcl:DefineAlias "$top.but91" "Button2_7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but92 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text * 
    vTcl:DefineAlias "$top.but92" "Button2_8" vTcl:WidgetProc "Toplevel1" 1
    button $top.but93 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$top.but93" "Button2_9" vTcl:WidgetProc "Toplevel1" 1
    button $top.but94 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #122E63 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 16 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$top.but94" "Button2_10" vTcl:WidgetProc "Toplevel1" 1
    button $top.but96 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #f2a343 -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 15 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text = 
    vTcl:DefineAlias "$top.but96" "Button3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 0 -relx 0.263 -y 0 -rely 0.04 -width 0 -relwidth 0.464 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.2 -width 0 -relwidth 0.179 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab45.ent52 \
        -in $top.lab45 -x 0 -relx 2.065 -y 0 -rely 2.195 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab45.lab53 \
        -in $top.lab45 -x 0 -relx 2.12 -y 0 -width 0 -relwidth 0.005 \
        -height 0 -relheight 5.146 -anchor nw -bordermode ignore 
    place $top.lab45.ent55 \
        -in $top.lab45 -x 0 -relx 1.793 -y 0 -rely 2.439 -width 254 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx -0.029 -y 0 -rely 0.36 -width 0 -relwidth 0.265 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.28 -width 0 -relwidth 0.209 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.039 -y 0 -rely 0.44 -width 0 -relwidth 0.189 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx -0.029 -y 0 -rely 0.52 -width 0 -relwidth 0.27 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -y 0 -rely 0.6 -width 0 -relwidth 0.233 -height 0 \
        -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.039 -y 0 -rely 0.68 -width 0 -relwidth 0.208 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.22 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.3 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.38 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.46 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.54 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent61 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.62 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent62 \
        -in $top -x 0 -relx 0.185 -y 0 -rely 0.7 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.37 -y 0 -rely 0.32 -width 0 -relwidth 0.16 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.37 -y 0 -rely 0.4 -width 0 -relwidth 0.161 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.37 -y 0 -rely 0.48 -width 0 -relwidth 0.16 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.37 -y 0 -rely 0.56 -width 0 -relwidth 0.16 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.37 -y 0 -rely 0.64 -width 0 -relwidth 0.16 \
        -height 0 -relheight 0.082 -anchor nw -bordermode ignore 
    place $top.ent69 \
        -in $top -x 0 -relx 0.486 -y 0 -rely 0.34 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent70 \
        -in $top -x 0 -relx 0.535 -y 0 -rely 0.42 -width 134 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent71 \
        -in $top -x 0 -relx 0.486 -y 0 -rely 0.5 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent72 \
        -in $top -x 0 -relx 0.506 -y 0 -rely 0.58 -width 164 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent73 \
        -in $top -x 0 -relx 0.486 -y 0 -rely 0.66 -width 184 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.039 -y 0 -rely 0.82 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.156 -y 0 -rely 0.82 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but76 \
        -in $top -x 0 -relx 0.272 -y 0 -rely 0.82 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but77 \
        -in $top -x 0 -relx 0.389 -y 0 -rely 0.82 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent78 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.2 -width 256 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but79 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.3 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but80 \
        -in $top -x 0 -relx 0.768 -y 0 -rely 0.3 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but81 \
        -in $top -x 0 -relx 0.837 -y 0 -rely 0.3 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but82 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.4 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but83 \
        -in $top -x 0 -relx 0.837 -y 0 -rely 0.4 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but84 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.5 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but85 \
        -in $top -x 0 -relx 0.768 -y 0 -rely 0.5 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but86 \
        -in $top -x 0 -relx 0.837 -y 0 -rely 0.5 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but87 \
        -in $top -x 0 -relx 0.768 -y 0 -rely 0.4 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but88 \
        -in $top -x 0 -relx 0.837 -y 0 -rely 0.6 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but89 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.6 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but90 \
        -in $top -x 0 -relx 0.768 -y 0 -rely 0.6 -width 67 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but91 \
        -in $top -x 0 -relx 0.905 -y 0 -rely 0.3 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but92 \
        -in $top -x 0 -relx 0.905 -y 0 -rely 0.4 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but93 \
        -in $top -x 0 -relx 0.905 -y 0 -rely 0.5 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but94 \
        -in $top -x 0 -relx 0.905 -y 0 -rely 0.6 -width 47 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but96 \
        -in $top -x 0 -relx 0.7 -y 0 -rely 0.7 -width 257 -relwidth 0 \
        -height 35 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

